server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Product Service
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-api/**
          filters:
            - RewritePath=/product-api(?<segment>/?.*), /api/products$\{segment}

        # Order Service
        - id: order-service-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-api/**
          filters:
            - RewritePath=/order-api(?<segment>/?.*), /api/orders$\{segment}

        # Inventory Service
        - id: inventory-service-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory-api/**
          filters:
            - RewritePath=/inventory-api(?<segment>/?.*), /api/inventory$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
